import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { randomBytes } from "node:crypto";

const ROOT = process.cwd();
const ENV_FILES = [".env", ".env.local"];
const MANAGED_KEYS = [
  "DS_MCP_REST_API_BEARER_TOKEN",
  "DS_MCP_MCP_BEARER_TOKEN",
  "DS_MCP_MCP_URL_SECRET",
  "DS_MCP_GITHUB_WEBHOOK_SECRET",
  "DS_MCP_INTERNAL_AGENT_RESULT_TOKEN"
];

function parseEnvFile(contents) {
  const output = {};
  for (const rawLine of contents.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const assignment = line.startsWith("export ") ? line.slice(7).trim() : line;
    const equalsIndex = assignment.indexOf("=");
    if (equalsIndex <= 0) continue;
    const key = assignment.slice(0, equalsIndex).trim();
    const value = assignment.slice(equalsIndex + 1).trim().replace(/^['"]|['"]$/g, "");
    if (key) output[key] = value;
  }
  return output;
}

function loadEnvFile(filePath) {
  if (!existsSync(filePath)) return {};
  return parseEnvFile(readFileSync(filePath, "utf8"));
}

function token() {
  return randomBytes(32).toString("hex");
}

function mask(value) {
  const text = String(value || "").trim();
  if (!text) return "unset";
  if (text.length <= 12) return text;
  return `${text.slice(0, 6)}...${text.slice(-4)}`;
}

function quote(value) {
  if (value === "") return "";
  if (/^[A-Za-z0-9_./:+-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

function readCurrentEnv() {
  return {
    ...loadEnvFile(resolve(ROOT, ".env")),
    ...loadEnvFile(resolve(ROOT, ".env.local")),
    ...process.env
  };
}

function reportAudit(current) {
  console.log(JSON.stringify({
    ok: true,
    root: ROOT,
    managed: MANAGED_KEYS.map((key) => ({
      key,
      configured: Boolean(current[key]),
      value: mask(current[key])
    }))
  }, null, 2));
}

function planRotate(current, keys) {
  const normalized = [...new Set(keys.map((key) => key.trim()).filter(Boolean))];
  if (normalized.length === 0) {
    throw new Error("No keys provided. Use --vars=KEY1,KEY2");
  }

  const plan = normalized.map((key) => {
    const next = token();
    return {
      key,
      old: mask(current[key]),
      next
    };
  });

  console.log(JSON.stringify({
    ok: true,
    action: "plan_rotate",
    note: "This tool only plans rotation. It does not execute vercel env commands.",
    plan,
    vercel_commands: plan.map(({ key, next }) => [
      `vercel env rm ${key} production`,
      `vercel env add ${key} production`
    ]).flat()
  }, null, 2));
}

function writeLocal(current, keys) {
  const normalized = [...new Set(keys.map((key) => key.trim()).filter(Boolean))];
  if (normalized.length === 0) {
    throw new Error("No keys provided. Use --vars=KEY1,KEY2");
  }

  const nextValues = new Map(normalized.map((key) => [key, token()]));
  const lines = [];
  for (const key of ENV_FILES) {
    const file = resolve(ROOT, key);
    if (!existsSync(file)) continue;
    const raw = readFileSync(file, "utf8").split(/\r?\n/);
    for (const line of raw) lines.push(line);
  }

  const merged = { ...current };
  for (const [key, value] of nextValues.entries()) {
    merged[key] = value;
  }

  const outputLines = [
    "# Generated by `npm run env:ops -- write-local --vars=...`",
    ...Object.entries(merged)
      .filter(([key]) => MANAGED_KEYS.includes(key))
      .map(([key, value]) => `${key}=${quote(value)}`)
  ];

  writeFileSync(resolve(ROOT, ".env.local"), `${outputLines.join("\n")}\n`);
  console.log(JSON.stringify({
    ok: true,
    action: "write_local",
    file: ".env.local",
    updated: normalized
  }, null, 2));
}

const argv = process.argv.slice(2);
const command = argv[0] || "audit";
const varsArg = argv.find((arg) => arg.startsWith("--vars="));
const vars = varsArg ? varsArg.slice("--vars=".length).split(",") : [];
const current = readCurrentEnv();

try {
  if (command === "audit") {
    reportAudit(current);
  } else if (command === "plan-rotate") {
    planRotate(current, vars);
  } else if (command === "write-local") {
    writeLocal(current, vars);
  } else {
    throw new Error(`Unknown command: ${command}`);
  }
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
